# Numpy - Numerical python


1. Allow several Mathematical Operations
2. Faster operations

search for numpy documentation and learn

In [1]:
import numpy as np

list vs numpy - time taken

In [ ]:
from time import process_time

time taken by a list

In [9]:
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.00048696100000000797


In [10]:
np_array = np.array([i for i  in range(10000)])

start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.00016309000000003238


# Numpy Arrays

In [12]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
# creating 1d array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [16]:
a.shape

(5,)

In [17]:
#ctrate 2d array
b =np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
b.shape

(2, 4)

In [19]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholders in numpy array

In [20]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# create an array of a perticular value
z = np.full((5,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [24]:
# create an identity matrix
#all diagonal value are one and rest zero
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.51133505 0.83027775 0.80011139 0.24956876]
 [0.48455982 0.39411786 0.19879108 0.68523384]
 [0.28515763 0.30049972 0.48696338 0.17612012]]


In [26]:
# random integer value array with specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[74 33 29 77 29]
 [27 80 37 24 24]
 [21 69 70 47 59]]


In [28]:
# create an array of evenly spaced values------specify no. of value required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [31]:
# array of evenly spaced values----- specifying the step
e = np.arange(10,30,5)
print(e)


[10 15 20 25]


In [35]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

# Analysing numpy array

In [36]:
c = np.random.randint(10,90,(4,4))
print(c)

[[48 83 79 49]
 [89 11 67 79]
 [39 26 21 87]
 [57 21 57 46]]


In [37]:
# array dimension
print(c.shape)

(4, 4)


In [38]:
# number of dimension
print(c.ndim)

2


In [39]:
# number of element in an array
print(c.size)

16


In [40]:
# check datatype of value in an array
print(c.dtype)

int64


# Mathematical operation on np array

In [41]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)    # concatenate list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)


[[4 5 2]
 [8 0 5]
 [2 1 0]]
[[10 17 10]
 [19 14 13]
 [15 11 16]]


In [48]:
from binascii import b2a_hex
print(a+b)

print(a-b)

print(a*b)

print(a/b)

[[14 22 12]
 [27 14 18]
 [17 12 16]]
[[ -6 -12  -8]
 [-11 -14  -8]
 [-13 -10 -16]]
[[ 40  85  20]
 [152   0  65]
 [ 30  11   0]]
[[0.4        0.29411765 0.2       ]
 [0.42105263 0.         0.38461538]
 [0.13333333 0.09090909 0.        ]]


another way of doing operation

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)


[[4 5 2]
 [8 0 5]
 [2 1 0]]
[[10 17 10]
 [19 14 13]
 [15 11 16]]


In [49]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 22 12]
 [27 14 18]
 [17 12 16]]
[[ -6 -12  -8]
 [-11 -14  -8]
 [-13 -10 -16]]
[[ 40  85  20]
 [152   0  65]
 [ 30  11   0]]
[[0.4        0.29411765 0.2       ]
 [0.42105263 0.         0.38461538]
 [0.13333333 0.09090909 0.        ]]


# Array Manupulation

In [4]:
import numpy as np

array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 3 4]
 [7 5 6]]
(2, 3)


In [5]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 7]
 [3 5]
 [4 6]]
(3, 2)


In [6]:
#another method of transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 7]
 [3 5]
 [4 6]]
(3, 2)


In [7]:
# reshaping array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 5 9]
 [9 5 5]]
(2, 3)


In [9]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 5]
 [9 9]
 [5 5]]
(3, 2)
