In [ ]:
import numpy as np

# create a matrix using numpy

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10,30],[44,77],[100,46]])
print(matrix_2)

[[ 10  30]
 [ 44  77]
 [100  46]]


In [ ]:
matrix_2.shape

(3, 2)

# create matrix with random values

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.88362533 0.84257647 0.03908824]
 [0.71659318 0.05402892 0.36126847]
 [0.35008254 0.10489885 0.11795851]]


In [ ]:
# create matrix with random integer

random_integer_matrix =np.random.randint(100,size = (5,5))
print(random_integer_matrix)

[[71 31 46 14 75]
 [49  2 29 27 70]
 [98  8 11 28 90]
 [92 22 59  2 88]
 [79 45 50 34 19]]


# matrix with value 1

In [ ]:
matrix_3 = np.ones((5,4))
print(matrix_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((5,4), dtype = int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# null matrix

In [ ]:
null_matrix = np.zeros((5,5))
print(null_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# identity matrix

In [ ]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# transpose of a matrix

In [ ]:
# matrix with random integer values
a = np.random.randint(100,size = (4,4))
print(a)

[[59 71 39 60]
 [19  0 56 87]
 [92 46 43 60]
 [18 29 61  0]]


In [ ]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[59 19 92 18]
 [71  0 46 29]
 [39 56 43 61]
 [60 87 60  0]]


# matrix addition

two matrices can be added only if they have same shape

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[30,70],[60,100]])

print(A)
print(B)

[[2 3]
 [4 5]]
[[ 30  70]
 [ 60 100]]


In [ ]:
A.shape

(2, 2)

In [ ]:
B.shape

(2, 2)

adding two matrix

In [ ]:
sum =  A +B
print(sum)

[[ 32  73]
 [ 64 105]]


In [ ]:
#create two matices with random values

matrix_1 = np.random.randint(100,size =(3,3))
matrix_2 = np.random.randint(100,size =(3,3))
print(matrix_1)
print(matrix_2)

[[41 96 85]
 [12 32 81]
 [39 43 17]]
[[ 9 38 62]
 [51 96  7]
 [70 61 17]]


In [ ]:
sum = np.add(matrix_1 , matrix_2)

In [ ]:
print(sum)

[[ 50 134 147]
 [ 63 128  88]
 [109 104  34]]


# matrix subtraction

In [ ]:
A = np.array([[2,3],[4,5]])

B = np.array([[30,70],[60,100]])

print(A)
print(B)

[[2 3]
 [4 5]]
[[ 30  70]
 [ 60 100]]


In [ ]:
difference = A -B
print(difference)

[[-28 -67]
 [-56 -95]]


In [ ]:
#create two matices with random values

matrix_1 = np.random.randint(100,size =(3,3))
matrix_2 = np.random.randint(100,size =(3,3))
print(matrix_1)
print(matrix_2)

[[51 76 87]
 [24 93 25]
 [59 15 29]]
[[61 99 57]
 [59 23 63]
 [53 29 80]]


In [ ]:
diff = np.subtract(matrix_1 , matrix_2)

In [ ]:
print(diff)

[[-10 -23  30]
 [-35  70 -38]
 [  6 -14 -51]]


# matrix multiplication

In [ ]:
x =4
y = np.random.randint(10, size =(4,4))

print(y)

[[5 5 5 5]
 [7 9 9 7]
 [5 7 3 7]
 [9 3 7 8]]


In [ ]:
product = np.multiply(x,y)
print(product)

[[20 20 20 20]
 [28 36 36 28]
 [20 28 12 28]
 [36 12 28 32]]


multiplying two matix

In [ ]:
matrix_1 = np.random.randint(10,size =(3,3))
matrix_2 = np.random.randint(10,size =(3,4))
print(matrix_1)
print(matrix_2)

[[9 0 4]
 [6 2 4]
 [8 1 7]]
[[3 0 1 2]
 [2 0 0 0]
 [7 2 3 2]]


In [ ]:
product = np.dot(matrix_1,matrix_2)

print(product)

[[55  8 21 26]
 [50  8 18 20]
 [75 14 29 30]]


In [ ]:
product.shape

(3, 4)

element wise multiplication

In [ ]:
# create two matices with random value

matrix_3 = np.random.randint(5, size = (3,3))
matrix_4 = np.random.randint(5, size = (3,3))

print(matrix_3)
print(matrix_4)

[[2 1 3]
 [2 2 1]
 [3 0 4]]
[[1 1 0]
 [0 0 3]
 [2 2 2]]


In [ ]:
product = np.multiply(matrix_3,matrix_4)
print(product)

[[2 1 0]
 [0 0 3]
 [6 0 8]]
